In [1]:
import numpy as np
import time



In [3]:
# Array Creation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 21).reshape(4, 5)

print("Array 1:", arr1)
print("Array 2:\n", arr2)



Array 1: [1 2 3 4 5]
Array 2:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# Indexing & Slicing
print("\nFirst Row:", arr2[0])
print("Last Column:", arr2[:, -1])
print("Sub Array:\n", arr2[1:3, 1:4])




First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20]
Sub Array:
 [[ 7  8  9]
 [12 13 14]]


In [9]:
# Mathematical Operations
print("\nAddition:", arr2 + 10)
print("Multiplication:", arr2 * 2)


Addition: [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Multiplication: [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [11]:
# Statistical Operations
print("\nMean:", np.mean(arr2))
print("Median:", np.median(arr2))
print("Max:", np.max(arr2))
print("Min:", np.min(arr2))
print("Sum (Axis=0):", np.sum(arr2, axis=0))


Mean: 10.5
Median: 10.5
Max: 20
Min: 1
Sum (Axis=0): [34 38 42 46 50]


In [13]:
# Reshaping
reshaped = arr2.reshape(5, 4)
print("\nReshaped Array:\n", reshaped)


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [15]:
# Broadcasting
b = np.array([1, 2, 3, 4, 5])
print("\nBroadcasting Result:\n", arr2 + b)



Broadcasting Result:
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]]


In [17]:
# Save & Load
np.save("data.npy", arr2)
loaded = np.load("data.npy")
print("\nLoaded Array:\n", loaded)



Loaded Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
# Performance Comparison
python_list = list(range(1000000))
numpy_array = np.arange(1000000)


In [23]:
# Python List
start = time.time()
result1 = [x * 2 for x in python_list]
end = time.time()
print("\nPython List Time:", end - start)


Python List Time: 0.07000064849853516
